@startuml

title MimirCMS
left to right direction

rectangle Client {
  [Web Browser]
}

cloud Internet {
}

node MimirCMS {
  [Artifact Service] --> [Artifact Store]
  [Artifact Store] --> [Thumbnail Generator]
  [Artifact Store] --> [Thumbnail Store]
  [Thumbnail Service] --> [Artifact Store]
  [Thumbnail Service] --> [Icon Service] : fallback
  [Folder Service] --> [Folder Store]
  [Authentication]
}

database MariaDB {
}

database OpenLDAP {
}

database "File System" as Filesystem {
}

[Web Browser] --> Internet
Internet --> [Artifact Service]
Internet --> [Thumbnail Service]
Internet --> [Icon Service]
Internet --> [Folder Service]
Internet --> [Authentication]
[Artifact Store] ---> MariaDB
[Artifact Store] --> Filesystem
[Thumbnail Store] --> Filesystem : write thumbnail
[Thumbnail Generator] --> Filesystem : read data
[Folder Store] ---> MariaDB
[Authentication] ----> OpenLDAP

@enduml