version: "3"
services:
  mimir:
    image: seproject/mimir:1.0.0
    container_name: mimir
    build:
      context: ./
      args:
        MIMIR_VERSION: 1.0.0
    ports:
      - "80:8080"
    environment:
      - SERVER_PORT=8080
  mail:
    image: namshi/smtp
    container_name: smtp-mimir
    restart: always
    expose:
     - "25"
    environment:
     - MAILNAME=owa.sonia.de
