version: "3"
services:
  nginx:
    image: seproject/mimir-frontend:1.0.0
    container_name: mimir-frontend
    build:
     context: ./frontend/
    ports:
      - "80:80"
    depends_on:
      - mimir

  mimir:
    image: seproject/mimir:1.0.0
    container_name: mimir
    build:
      context: ./
      args:
        MIMIR_VERSION: 1.0.0
    depends_on:
      - openldap
      - mariadb
      - mail
    environment:
      - SERVER_PORT=8080
      - USER_AUTHENTICATION_LDAP_USERSEARCHFILTER=(uid={0})
      - USER_AUTHENTICATION_LDAP_USERSEARCHBASE=ou=users
      - USER_AUTHENTICATION_LDAP_URL=ldap://openldap
      - USER_AUTHENTICATION_LDAP_PORT=389
      - USER_AUTHENTICATION_LDAP_USERNAME=cn=admin,dc=seprojekt,dc=de
      - USER_AUTHENTICATION_LDAP_PASSWORD=cmsadmin
      - USER_AUTHENTICATION_LDAP_ROOT=dc=seprojekt,dc=de
      - SPRING_DATASOURCE_URL=jdbc:mysql://mariadb/cms?useUnicode=yes&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=cms
      - SPRING_DATASOURCE_PASSWORD=cms
    volumes:
      - ./container_volumes/mimir/data:/srv/mimir

  openldap:
    image: osixia/openldap
    container_name: openldap
    command: -l debug --copy-service
    ports:
      - "389:389"
    environment:
      - LDAP_ORGANISATION=SEProjekt Test Organisation
      - LDAP_DOMAIN=seprojekt.de
      - LDAP_BASE_DN=dc=seprojekt,dc=de
      - LDAP_ADMIN_PASSWORD=cmsadmin
      - LDAP_TLS=false
    volumes:
      - ./container_volumes/openldap/data:/var/lib/ldap
      - ./container_volumes/openldap/config:/etc/ldap/slapd.d
      - ./src/main/resources/ldap_schema.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/cms.ldif

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=cms
      - MYSQL_USER=cms
      - MYSQL_PASSWORD=cms
      # https://github.com/docker-library/mariadb/issues/262
      - MYSQL_INITDB_SKIP_TZINFO=1
    volumes:
      - ./container_volumes/mariadb/data:/var/lib/mysql

  mail:
    image: namshi/smtp
    container_name: smtp-mimir
    restart: always
    environment:
     - MAILNAME=owa.sonia.de

