@startuml

frame Deplyoment-CMS++{
    
    cloud ExternalMailServer
    
    Browser -- nginx : HTTP <<protocol>>
    nginx -- Tomcat : HTTP <<protocol>>
    Tomcat -- OpenLDAP : LDAP <<protocol>>
    Tomcat -- MariaDB : MySQL <<protocol>>
    Tomcat -- EximSMTP : SMTP <<protocol>>
    EximSMTP -- ExternalMailServer : SMTP <<protocol>>
    
    node Client {
        node Linux/Windows <<OS>> {
            node Browser <<Service>> {

            }
        }
    }

    node Server {
        node Linux <<OS>> {
           node DockerHost <<Host>> {
                node seproject/mimir <<Service>> {
                    node Debian-Buster-Slim <<OS>> {
                        node Tomcat <<Application-Server>> {
                            node JVM <<Execution-Environment>> {
                               artifact "mimir.jar" <<artifact>>
                            }
                        }
                    }
                }
                node seproject/mimir-frontend <<Service>> {
                    node debian-buster-slim <<OS>> {
                        node nginx <<WebServer>> {
                            artifact "Mimir-Frontend" <<artifact>>
                        }
                    }
                }
                node mariadb <<Service>> {
                    node ubuntu-bionic <<OS>> {
                        node MariaDB <<Database-System>> {
                        }
                    }
                }
                node osixia/openldap <<Service>> {
                    node debian-strech-slim <<OS>> {
                        node OpenLDAP <<Service>> {
                        }
                    }
                }
                node namshi/smtp <<Service>> {
                    node debian:buster <<OS>> {
                        node EximSMTP <<Service>> {
                        }
                    }
                }
                node LdapData <<Volume>> {
                }
                node DbData <<Volume>> {
                }
                LdapData -- OpenLDAP
                DbData -- MariaDB
           }
           node DockerCompose <<Service>> {
                artifact "docker-compose.yml" <<artifact>>
           }
           DockerCompose -- DockerHost : <<configure>>
          
        }
    }
}
@enduml
