@startuml

frame Deployment-CMS++{
    
    cloud OstfaliaMailServer
    
    Browser -- nginx : HTTP <<protocol>>
    nginx -- Tomcat : HTTP (proxy-pass) <<protocol>>
    Tomcat -- OpenLDAP : LDAP <<protocol>>
    Tomcat -- MariaDB : MySQL <<protocol>>
    Tomcat -- EximSMTP : SMTP <<protocol>>
    EximSMTP -- OstfaliaMailServer : SMTP <<protocol>>
    
    node Client {
        node Linux/Windows <<OS>> {
            node Browser <<Service>> {

            }
        }
    }

    node Server {
        node Linux <<OS>> {
           node DockerHost <<Host>> {
                node seproject/mimir <<Service>> {
                    node Debian-Buster-Slim <<OS>> {
                        node Tomcat <<Application-Server>> {
                            node JVM <<Execution-Environment>> {
                               artifact "mimir.jar" <<artifact>>
                            }
                        }
                    }
                }
                node seproject/mimir-frontend <<Service>> {
                    node debian-buster-slim <<OS>> {
                        node nginx <<WebServer>> {
                            artifact "Mimir-Frontend" <<artifact>>
                        }
                    }
                }
                node mariadb <<Service>> {
                    node ubuntu-bionic <<OS>> {
                        node MariaDB <<Database-System>> {
                        }
                    }
                }
                node OsixiaOpenldap <<Service>> {
                    node debian-strech-slim <<OS>> {
                        node OpenLDAP <<Service>> {
                        }
                    }
                }
                node NamshiSmtp <<Service>> {
                    node debian:buster <<OS>> {
                        node EximSMTP <<Service>> {
                        }
                    }
                }
                node LdapData <<Volume>> {
                }
                node DbData <<Volume>> {
                }
                LdapData -- OsixiaOpenldap
                DbData -- mariadb
           }
           node DockerCompose <<Tool>> {
                artifact "docker-compose.yml" <<artifact>>
           }
           DockerCompose -- DockerHost : <<configure>>
          
        }
    }
}
@enduml
